### ISSUE TITLE
[alpha v0.2] does not find `/vita2hos/test.elf`

### ISSUE THREAD

**Issue by anazeusMX** [xerpi/vita2hos#10]
Hello its good to see that new version was just released. I have a problem with this new version where I cannot enter the menu after launching it. I have no problem with the previous version but this time I cannot enter the menu. Thanks in advice!

**Comment by jeliebig** [comment]
I'll ask a few question to understand your problem better.

What menu are you talking about - the CHIP-8 one?
Are you testing on a real switch?
What do you do to enter the menu? What happens when you do it now?

**Comment by anazeusMX** [comment]
> I'll ask a few question to understand your problem better.
> 
> What menu are you talking about - the CHIP-8 one? Are you testing on a real switch? What do you do to enter the menu? What happens when you do it now?

Yes the chip-8 one. Im using the same way as the last one by holding the R trigger to enter the menu. I switch back to the last version (alpha 0.1) and its working fine but when I try to replace the vita2hos.nsp from the new one I got this error "Error code:2-0000 - Error loading Playstation Vita executable"

I already create a vita2hos folder and move the .elf to it. I dont know what happened maybe I miss something or do something wrong.

**Comment by TSRBerry** [comment]
With the release of [alpha-0.3](https://github.com/xerpi/vita2hos/releases/tag/alpha-0.3) this problem should now be fixed.

Although there are other problems now that prevent it from working on real hardware, at least this issue can now be closed. :D
