### ISSUE TITLE
[Proposition] Vita games on homescreen

### ISSUE THREAD

**Issue by HackZy01** [xerpi/vita2hos#11]
When it supports at least GPU stuff, make it that it shows Vita software on the HOS Home Screen, with all original icon0, it would make it look really good

**Comment by jeliebig** [comment]
Sadly that's not possible.

Forwarders are considered piracy and are not supported.

**Comment by Masamune3210** [comment]
And before people start complaining, this is the same belief that a lot of devs have. If it requires sigpatches, it's piracy.

**Comment by jeliebig** [comment]
It's not about what devs "believe" more so about how Nintendo sees it. Everything that is piracy for Nintendo should also be considered piracy for us. It's better for everyone this way.

**Comment by impeeza** [comment]
no aiming to pour gas on fire, but for Nintendo emulation is illegal, even if they sell emulators for theirs consoles, but I understand the fact what anybody wants to be far as possible from piracy.

**Comment by Masamune3210** [comment]
> It's not about what devs "believe" more so about how Nintendo sees it. Everything that is piracy for Nintendo should also be considered piracy for us. It's better for everyone this way.

Yeah that's true, the farther outside of their radar, the better
