### ISSUE TITLE
VPK support ?

### ISSUE THREAD

**Issue by LeTartimorphe** [xerpi/vita2hos#13]
Hello, I tried for hours to change a VPK file into a Velf ou Self but nothing where good, so do you have tutorial to switch from VPK to a valid file or just a support for all VPK files

**Comment by takoyaki99** [comment]
They provide useable code in VELF or SELF format, if you want to run a game it’s not possible to do so (yet). I think the files used are usually for development purposes as well

**Comment by xerpi** [comment]
A VPK is actually just a ZIP file. You can change the extension and extract the contents. You'll see a file named `eboot.bin`, that's a SELF.
I'll add VPK support in a future release.

**Comment by LeTartimorphe** [comment]
okay thanks, i effectively could get the file eboot.bin, but now i feel pretty dumb, i put the file inside the "test.elf" (and tried to put it in other folder too, maybe it could work by magic but nah..) I only get error 2-AW7NA-0000 ; "Make sure to place it to /test.elf"

what did I do wrong ?

**Comment by xerpi** [comment]
`test.elf` is the name of the file. You have to rename `eboot.bin` to `test.elf` (and not create a folder named `test.elf`).

**Comment by LeTartimorphe** [comment]
That's done !  . . . Hm . . It's still not working, same error . . . My eboot.bin has been renamed as test.elf, inside vita2hos folder, maybe the path is wrong ? vita2hos need to be at the root of sd card right ? (I also tried to put it inside Atmosphere folder but ain't working either...) I feel really bad to fail so much for something that look so easy to do . . .
![github2](https://user-images.githubusercontent.com/101837142/161019388-5c860d50-1afd-4405-9f76-328f903567fa.PNG)
![github1](https://user-images.githubusercontent.com/101837142/161019407-74492815-2e9a-4c2c-af08-17be205b8d7b.PNG)

**Comment by xerpi** [comment]
For alpha 0.1 it goes in the root of the SD, not inside the vita2hos folder.

**Comment by LeTartimorphe** [comment]
I just tried to put it at the root of SD, but didn't work either, file's name is supposed to be "test.elf" ? there's no mistake in file ? i think I have 0.1 in fact, maybe the config file is different between 0.1 and 0.2 ?

**Comment by xerpi** [comment]
Make sure the Windows file explorer is not hiding the extension, otherwise it would end up like `test.elf.something`.
I deleted 0.2 because it has bugs, so right now only 0.1 is available/downloadable.

**Comment by LeTartimorphe** [comment]
ok, i'll give a try when i'll get free time thx for help btw

**Comment by LeTartimorphe** [comment]
so, nope, the extension is really a .elf, same as the screenshot posted before

**Comment by xerpi** [comment]
Does it work with the example files I provide?

**Comment by LeTartimorphe** [comment]
where can i get this exemple file ?

**Comment by xerpi** [comment]
https://github.com/xerpi/vita2hos/releases
Where it says "Sample PSVita homebrew".

**Comment by LeTartimorphe** [comment]
so, it worked, i could start it but crashed after some second "context: dkDeviceDestroy, message: unfreed memory blocks, result 9"

**Comment by xerpi** [comment]
Try the ones linked on the 0.1 release.

**Comment by LeTartimorphe** [comment]
eh . . . yeah, i'm absolutely dumb, i pick the wrong one . . . so yeah, i got the triangle repeating when i start it

**Comment by LeTartimorphe** [comment]
The game I choose to run with 0.1 realease could be too big and don't work ?

**Comment by xerpi** [comment]
Initial vpk support has been implement here: https://github.com/xerpi/vita2hos/commit/2f51ed657be4d9e5cdf08ffc01cf16756c67ee5f
Note that it only looks for a file called eboot.bin inside the vpk and it doesn't decompress/install the package, so if the vpk contains data (such as textures or audio) the program will not be able to find it.
