### ISSUE TITLE
override_config.ini crashes hbmenu when in /atmosphere/config

### ISSUE THREAD

**Issue by ZombieBrine13092** [xerpi/vita2hos#22]
Self-explanatory. I'm using the default config provided in the README, and an error (seen in the attached image) is reported upon any attempt to launch hbmenu.
![219171F6-CC3F-4A95-A71F-002873EE0D01](https://user-images.githubusercontent.com/51412993/169723206-cf0e1bfc-3f4e-42a7-b3c4-f0956828ccbf.jpg)

**Comment by ZombieBrine13092** [comment]
didn't read more, this happens in alpha 0.1 and alpha 0.2 is currently download-less right now

**Comment by jeliebig** [comment]
While using the config provided in the Readme, you are not able to launch the hbmenu. You need to remove the config or rename it to be able to access hbmenu again.
