### ISSUE TITLE
Issue building, missing "libnx32/switch32_rules"

### ISSUE THREAD

**Issue by GarnetSunset** [xerpi/vita2hos#26]
`root@7c0b94cf994d:/downloads/Downloads/vita2hos# make
Makefile:10: /opt/devkitpro/libnx32/switch32_rules: No such file or directory
make: *** No rule to make target '/opt/devkitpro/libnx32/switch32_rules'.  Stop.`

From the official devkita64 image.

**Comment by xerpi** [comment]
You need a private version of devkitARM to build vita2hos.
If you are a developer willing to contribute we can hice you access to a Docker container with all the toolchain installed.

**Comment by GarnetSunset** [comment]
Ahh okay, that's alright! Sorry, didn't realize it was private. :)
