### ISSUE TITLE
[Suggestion] Vita2Hos Discord Server

### ISSUE THREAD

**Issue by Volcan4436** [xerpi/vita2hos#28]
A discord server for this project would make it easier for you to share changes and talk to people who are using this and want to show issues with it.

just a suggestion i don't expect you to do it just thought it would be cool to be able to talk to others who like this project

**Comment by TSRBerry** [comment]
I'm not opposed to a discord server, but I think xerpi needs to make that decision. :D

But issues and suggestions should be reported here. That helps keeping things a bit more organized, I think.

**Comment by xerpi** [comment]
I've opened a server: https://discord.gg/Z9kAsBqkbx
It should be used for more casual conversation. As @TSRBerry mentioned, technical issues should be reported here.
